post http://localhost:3000/hospital/create
Content-Type: application/json

{
    "name": "lasu hospital",
    "hospitalType": "Public",
    "address": "123 Main St, City, State, Zip",
    "contactEmail": "encrane04@example.com"
}